Support OpenUPM
poi-vrc/DressingTools pull request #438
Opened 2024-12-17 21:21 UTC by yuna0x0

Add OpenUPM support for DressingTools.

---

[OpenUPM](https://openupm.com) is a package registry for open-source Unity packages. It can handle package updates and dependencies properly compared to UPM Git URL.

Personally, I recommended to use OpenUPM for installation if user is not using VCC. Especially for users who are not using DressingTools for VRChat.

Users can benefit from package updates and automatic dependencies resolving that OpenUPM (Unity scoped registry) provides.

---

In order to support OpenUPM, DressingTools' dependencies `AvatarLib` and `DressingFramework` have been added to `dependencies` property in `package.json`.

Hence, in the future user will have to install `AvatarLib` and `DressingFramework` first, then `DressingTools`. Otherwise, Unity will refuse to install DressingTools because its dependencies are not fulfilled.

---

Both English and Chinese (Traditional) documentations are updated.
For Japanese, because I am not a fluent Japanese translator, I am unable to help with the Japanese documentation.

---
OpenUPM page for `DressingTools` and its dependencies:

DressingTools:
https://openupm.com/packages/com.chocopoi.vrc.dressingtools/

DressingFramework:
https://openupm.com/packages/com.chocopoi.vrc.dressingframework/

AvatarLib:
https://openupm.com/packages/com.chocopoi.vrc.avatarlib/

2024-12-28 14:29 UTC, poi-vrc commented
Thank you for the pull request. I have considered about OpenUPM support before when VCC hasn't come out yet.

But since VCC uses an alternative approach other than using the Unity scoped registry approach. I am concerned about both Unity will try to obtain UPM packages listed in `dependencies` from the scoped registries, while VCC downloads zip packages listed in `vpmDependencies` into the `Packages` folder.

Would this cause a conflict or confuse Unity to search the packages from scoped registries while OpenUPM scope is not installed? I think Unity prioritizes project embedded packages placed inside the `Packages` more than the one downloaded by UPM though.

2024-12-30 00:03 UTC, yuna0x0 commented
After doing some in depth testing.

No, this won't cause a conflict or confuse Unity while OpenUPM scope is not installed.
Unity will list out the dependencies as custom packages.

![Screenshot_20241230_070815](https://github.com/user-attachments/assets/a1ce7398-b1ef-44b0-b777-6fbeb2b4f563)

---

If user have the package installed via VCC while OpenUPM scope is installed. Unity still prioritizes `Custom` packages placed in the `Packages` folder.

However, users might be confused by package manager as it will display it's coming from a scoped registry while it's actually using a custom one placed in the `Packages` folder.

Therefore, it's worth adding a recommendation for user to add the package using only one of the documented method, do not mix and match.

![Screenshot_20241230_073734](https://github.com/user-attachments/assets/228c76c2-ce94-4f19-8027-380bef3b05a2)

2024-12-30 08:06 UTC, poi-vrc requested changes

2024-12-30 08:06 UTC, poi-vrc commented on package.json
> +        "com.chocopoi.vrc.dressingframework": "2.1.1"
I think these should follow the same values listed in `vpmDependencies`

2024-12-30 08:06 UTC, poi-vrc commented on docs~/docs/getting-started/installation.md
> +    - [https://openupm.com/packages/com.chocopoi.vrc.dressingtools/](https://openupm.com/packages/com.chocopoi.vrc.dressingtools/)
IMO, it might be more preferable to list the OpenUPM scoped registry setup in our documentation instead of redirecting them to OpenUPM's docs.

2024-12-30 08:14 UTC, poi-vrc commented
Thanks for your further testing. I think there might have a few more things to address before we can merge this PR.

- Beta/pre-release version compatibility - whether the pre-release versions can be installed via OpenUPM without problems.
- Japanese documentation (I will help you to finish this after fixing the other languages' docs)
- Do we have to remove the UPM Git URL, ZIP options from the docs for clarity?
- `Library/PackageCache/xxx.xxx.xxx` and `Packages/xxx.xxx.xxx` compatibility
  - I think UPM install to the library packagecache instead. I am not sure about the compatibility if I am trying to access a `Packages/xxx.xxx.xxx/somefile.txt` in code, will it read the correct file from `Library/PackageCache/xxx.xxx.xxx/somefile.txt` (I think the concern exists with UPM Git URL though)

2024-12-30 08:16 UTC, poi-vrc commented
Since the project follows conventional commit, please change the commit message to
`chore: update package.json to support OpenUPM`

2024-12-30 08:24 UTC, poi-vrc commented
I think we could try including this OpenUPM support into 2.6.0-beta.1 (the version coming this week). And allows you to test installing this pre-release version.

2025-01-02 15:31 UTC, yuna0x0 commented on package.json
> +        "com.chocopoi.vrc.dressingframework": "2.1.1"
Great catch here. However, it seems like UPM doesn't support SemVer range syntax currently. Using the same values listed in `vpmDependencies` will cause Unity to throw an error and refuse to import the dependencies.

Unity only supports per project configuration using `resolutionStrategy` which can only sets all dependencies' SemVer range rule instead of per dependency in `package.json` file.

This will cause the different dependencies resolution logic between VPM (VCC) and UPM. Because Unity default uses `lowest` mode (Use exactly the requested version) of `resolutionStrategy`.

Though, this won't break the ability to import the package from VPM (VCC) into Unity even when the dependencies version doesn't match Unity's resolution strategy. Unity still prioritizes using whatever custom package that's placed in the `Packages/` folder, regardless of the package version in it.

We might have to mention this different in the documentation or consider another workaround to achieve the similar resolution logic.

References:
- https://discussions.unity.com/t/semantic-versioning-like-1-0-x-is-not-working/736812/3
- https://docs.unity3d.com/2022.3/Documentation/Manual/upm-manifestPkg.html
- https://docs.unity3d.com/2022.3/Documentation/Manual/upm-manifestPrj.html
- https://github.com/npm/node-semver?tab=readme-ov-file#caret-ranges-123-025-004

2025-01-02 15:51 UTC, yuna0x0 commented
> Do we have to remove the UPM Git URL, ZIP options from the docs for clarity?

I don't think we should remove the UPM Git URL and ZIP options from the docs entirely. As there might be users that still need the option to install it via Git URL or ZIP files (Eg, offline network environment, or corporate network limitation).

For clarity, I recommend we can hide those options inside things like HTML `<details>` (or similar shortcode in your SSG) named `Advanced` or something.

> `Library/PackageCache/xxx.xxx.xxx` and `Packages/xxx.xxx.xxx` compatibility

I am also not sure about the compatibility if we are trying to access a `Packages/xxx.xxx.xxx/somefile.txt` in code. I'll have to test it out.

2025-01-02 21:51 UTC, yuna0x0 commented
After testing, Unity will read files correctly from `Library/PackageCache/xxx.xxx.xxx/somefile.txt` when using path `Packages/xxx.xxx.xxx/somefile.txt`.

<img width="1508" alt="Screenshot 2025-01-03 at 4 13 26 AM" src="https://github.com/user-attachments/assets/ff625d54-99f4-43c7-89ed-a518f834cbf5" />

Packages that use a scoped registry will be imported into Unity's Asset Database just like custom packages. The only difference is that its entire package folder will be immutable. Therefore, your code can only read but not modify the content in the package.

Also, due to its immutability, any files in the package that are missing their corresponding Unity `.meta` files will also not be generated by Unity. Hence, Unity will keep throwing errors and refuse to import those files.

<img width="1498" alt="Screenshot 2025-01-03 at 5 48 47 AM" src="https://github.com/user-attachments/assets/173f8536-3c89-41ae-b43e-30d1be68b384" />

We should generate those missing `.meta` files (if any are missing) before this PR is merged.
From my observation, both `com.chocopoi.vrc.avatarlib` and `com.chocopoi.vrc.dressingframework` have files that are missing required `.meta` files.

2025-01-03 10:25 UTC, poi-vrc commented on package.json
> +        "com.chocopoi.vrc.dressingframework": "2.1.1"
Thanks for clarifying. I should have referred to the Unity documentation and checked about it.
That would be a bit annoying to keep changing the version once I updated other packages though.
We will keep this for now.

2025-01-03 10:26 UTC, poi-vrc commented
I will fix the missing meta files by promoting a new patch version for each two packages.

2025-01-03 20:53 UTC, yuna0x0 commented on docs~/docs/getting-started/installation.md
> +    - [https://openupm.com/packages/com.chocopoi.vrc.dressingtools/](https://openupm.com/packages/com.chocopoi.vrc.dressingtools/)
Updated the docs with OpenUPM scoped registry setup in our documentation.

2025-07-13 09:01 UTC, poi-vrc approved these changes

2025-07-13 09:02 UTC, poi-vrc approved these changes

2025-07-13 09:02 UTC, merged